
-- 1. Select all records from the REGISTRO_PORTAFOLIO table
SELECT * FROM REGISTRO_PORTAFOLIO
/

-- 2. Select all records from the USUARIO table

SELECT * FROM USUARIO
/

-- 3. Select all records from the ARCHIVO_DOCUMENTO table
SELECT * FROM ARCHIVO_DOCUMENTO
/


SELECT * FROM CATALOGO
/

SELECT * FROM CATALOGO_ITEM
/

SELECT * FROM UNIDAD_ORGANICA
/

SELECT * FROM UNIDAD_EJECUTORA
/

SELECT * FROM EVENTO_AUDITORIA
/